export const surpriseMePrompts = [
  'Una silla con forma de palta',
  'una pintura al óleo surrealista de ensueño de Salvador Dalí de un gato jugando a las damas',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'una pintura al óleo de Matisse de un robot humanoide jugando al ajedrez',
  'panda científico loco mezclando productos químicos brillantes, arte digital',
  "una fotografía macro de 35 mm de dos ratones en Hawái, cada uno con trajes de baño diminutos y tablas de surf diminutas, arte digital",
  'Representación 3D de un lindo pez tropical en un acuario sobre un fondo azul oscuro, arte digital',
  'un astronauta descansando en un resort tropical en el espacio, vaporwave',
  'un retrato de pintura al óleo de un capibara con túnicas reales medievales y una corona ornamentada sobre un fondo oscuro',
  'un vidrio con la figura de una hamburguesa y papas fritas',
  'un dibujo a lápiz y acuarela de una ciudad brillante en el futuro con autos voladores',
  'un salón interior iluminado por el sol con una piscina con agua clara y otra piscina con agua translúcida de color rosa pastel, junto a una gran ventana, arte digital',
  'un shiba inu adivino que lee tu destino en una hamburguesa gigante, arte digital',
  'una nutria marina con un pendiente de perla" de Johannes Vermeer',
  'una pintura de un gato molesto en el espacio',
  'una pintura de un zorro al estilo de Starry Night',
  'un plato de sopa que parece un monstruo, tejido con lana',
  'Un robot de peluche sentado contra una pared amarilla',
  'Una puesta de sol estilo synthwave sobre el agua reflectante del mar, arte digital',
  'Dos torres futuristas con un puente aéreo cubierto de exuberante vegetación, arte digital',
  'Una representación 3D de un globo aerostático de color arcoíris que vuela sobre un lago reflectante',
  'Una portada de cómic de un superhéroe con auriculares',
  'una cascada cristalina de noche con luna llena',
  'Una foto de un perro samoyedo con la lengua afuera abrazando a un gato siamés blanco',
  'Una foto de un monstruo de piel blanca parado en una habitación morada.',
  'Una foto de la escultura de David de Miguel Ángel con auriculares',
  'Un samurái montando un caballo en Marte, lomography.',
  'Un Cadillac moderno y elegante conduciendo por la autopista Gardiner con el centro de Toronto al fondo, con un destello de lente, fotografía de 50 mm',
  'Una fotografía realista de una mujer joven con ojos azules y cabello rubio',
  'Un hombre parado frente a un portal estelar a otra dimensión.',
  'Bob Esponja con Pantalones Cuadrados en el Proyecto de la Bruja de Blair',
  'Un velociraptor trabajando en un puesto de hotdogs',
  'Un hombre que camina por las bulliciosas calles de Kowloon por la noche, iluminado por muchos letreros de tiendas de neón brillante, lente de 50 mm',
  'Un automovil vivo, al estilo de una película de animación de Pixar',
  'Un club de baile cyborg futurista, con luces de neón.',
  'Star Wars en versión anime',
  'Una hamburguesa en forma de cubo de Rubik, fotografía profesional de alimentos',
  'Un erizo Synthwave, Blade Runner Cyberpunk',
  'Un astronauta que se encuentra con una forma de vida extraterrestre en un planeta distante, fotografía realista',
  'Un dinosaurio explorando Ciudad del Cabo, fotografía',
  'Un hombre que se enamora de su computadora, arte digital',
  'Una fotografía de un cyborg explorando Tokio de noche, lomography',
  'Constantinopla en el siglo XV 4k',
  'avión de onda sintética',
  'Un hombre deambula por las calles lluviosas de Tokio, con brillantes letreros de neón, 50 mm.',
  'Un transbordador espacial sobrevolando Ciudad del Cabo, arte digital',
]